/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as GatedRouteImport } from './routes/_gated'
import { Route as MarketingRouteImport } from './routes/_marketing'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as GatedDashboardRouteImport } from './routes/_gated/dashboard'
import { Route as MarketingIndexRouteImport } from './routes/_marketing/index'
import { Route as MarketingBlogRouteImport } from './routes/_marketing/blog'
import { Route as MarketingLegalRouteImport } from './routes/_marketing/legal'
import { Route as ApiOgRouteImport } from './routes/api/og'
import { Route as MarketingBlogIndexRouteImport } from './routes/_marketing/blog/index'
import { Route as MarketingBlogSlugRouteImport } from './routes/_marketing/blog/$slug'
import { Route as MarketingLegalIndexRouteImport } from './routes/_marketing/legal/index'
import { Route as MarketingLegalSlugRouteImport } from './routes/_marketing/legal/$slug'
import { Route as MarketingProductsSlugRouteImport } from './routes/_marketing/products/$slug'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const GatedRoute = GatedRouteImport.update({
  id: '/_gated',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingRoute = MarketingRouteImport.update({
  id: '/_marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const GatedDashboardRoute = GatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => GatedRoute,
} as any)
const MarketingIndexRoute = MarketingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingBlogRoute = MarketingBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingLegalRoute = MarketingLegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => MarketingRoute,
} as any)
const ApiOgRoute = ApiOgRouteImport.update({
  id: '/api/og',
  path: '/api/og',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingBlogIndexRoute = MarketingBlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MarketingBlogRoute,
} as any)
const MarketingBlogSlugRoute = MarketingBlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => MarketingBlogRoute,
} as any)
const MarketingLegalIndexRoute = MarketingLegalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MarketingLegalRoute,
} as any)
const MarketingLegalSlugRoute = MarketingLegalSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => MarketingLegalRoute,
} as any)
const MarketingProductsSlugRoute = MarketingProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => MarketingRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof MarketingIndexRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/login': typeof AuthLoginRoute
  '/dashboard': typeof GatedDashboardRoute
  '/blog': typeof MarketingBlogRouteWithChildren
  '/legal': typeof MarketingLegalRouteWithChildren
  '/api/og': typeof ApiOgRoute
  '/blog/$slug': typeof MarketingBlogSlugRoute
  '/legal/$slug': typeof MarketingLegalSlugRoute
  '/products/$slug': typeof MarketingProductsSlugRoute
  '/blog/': typeof MarketingBlogIndexRoute
  '/legal/': typeof MarketingLegalIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof MarketingIndexRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/login': typeof AuthLoginRoute
  '/dashboard': typeof GatedDashboardRoute
  '/api/og': typeof ApiOgRoute
  '/blog/$slug': typeof MarketingBlogSlugRoute
  '/legal/$slug': typeof MarketingLegalSlugRoute
  '/products/$slug': typeof MarketingProductsSlugRoute
  '/blog': typeof MarketingBlogIndexRoute
  '/legal': typeof MarketingLegalIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_gated': typeof GatedRouteWithChildren
  '/_marketing': typeof MarketingRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_gated/dashboard': typeof GatedDashboardRoute
  '/_marketing/blog': typeof MarketingBlogRouteWithChildren
  '/_marketing/legal': typeof MarketingLegalRouteWithChildren
  '/api/og': typeof ApiOgRoute
  '/_marketing/': typeof MarketingIndexRoute
  '/_marketing/blog/$slug': typeof MarketingBlogSlugRoute
  '/_marketing/legal/$slug': typeof MarketingLegalSlugRoute
  '/_marketing/products/$slug': typeof MarketingProductsSlugRoute
  '/_marketing/blog/': typeof MarketingBlogIndexRoute
  '/_marketing/legal/': typeof MarketingLegalIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/login'
    | '/dashboard'
    | '/blog'
    | '/legal'
    | '/api/og'
    | '/blog/$slug'
    | '/legal/$slug'
    | '/products/$slug'
    | '/blog/'
    | '/legal/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/login'
    | '/dashboard'
    | '/api/og'
    | '/blog/$slug'
    | '/legal/$slug'
    | '/products/$slug'
    | '/blog'
    | '/legal'
  id:
    | '__root__'
    | '/_auth'
    | '/_gated'
    | '/_marketing'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/_auth/login'
    | '/_gated/dashboard'
    | '/_marketing/blog'
    | '/_marketing/legal'
    | '/api/og'
    | '/_marketing/'
    | '/_marketing/blog/$slug'
    | '/_marketing/legal/$slug'
    | '/_marketing/products/$slug'
    | '/_marketing/blog/'
    | '/_marketing/legal/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  GatedRoute: typeof GatedRouteWithChildren
  MarketingRoute: typeof MarketingRouteWithChildren
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiOgRoute: typeof ApiOgRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_gated': {
      id: '/_gated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof GatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing': {
      id: '/_marketing'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_gated/dashboard': {
      id: '/_gated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof GatedDashboardRouteImport
      parentRoute: typeof GatedRoute
    }
    '/_marketing/': {
      id: '/_marketing/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MarketingIndexRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/blog': {
      id: '/_marketing/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof MarketingBlogRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/legal': {
      id: '/_marketing/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof MarketingLegalRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/api/og': {
      id: '/api/og'
      path: '/api/og'
      fullPath: '/api/og'
      preLoaderRoute: typeof ApiOgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing/blog/': {
      id: '/_marketing/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof MarketingBlogIndexRouteImport
      parentRoute: typeof MarketingBlogRoute
    }
    '/_marketing/blog/$slug': {
      id: '/_marketing/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof MarketingBlogSlugRouteImport
      parentRoute: typeof MarketingBlogRoute
    }
    '/_marketing/legal/': {
      id: '/_marketing/legal/'
      path: '/'
      fullPath: '/legal/'
      preLoaderRoute: typeof MarketingLegalIndexRouteImport
      parentRoute: typeof MarketingLegalRoute
    }
    '/_marketing/legal/$slug': {
      id: '/_marketing/legal/$slug'
      path: '/$slug'
      fullPath: '/legal/$slug'
      preLoaderRoute: typeof MarketingLegalSlugRouteImport
      parentRoute: typeof MarketingLegalRoute
    }
    '/_marketing/products/$slug': {
      id: '/_marketing/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof MarketingProductsSlugRouteImport
      parentRoute: typeof MarketingRoute
    }
  }
}

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface GatedRouteChildren {
  GatedDashboardRoute: typeof GatedDashboardRoute
}

const GatedRouteChildren: GatedRouteChildren = {
  GatedDashboardRoute: GatedDashboardRoute,
}

const GatedRouteWithChildren = GatedRoute._addFileChildren(GatedRouteChildren)

interface MarketingBlogRouteChildren {
  MarketingBlogSlugRoute: typeof MarketingBlogSlugRoute
  MarketingBlogIndexRoute: typeof MarketingBlogIndexRoute
}

const MarketingBlogRouteChildren: MarketingBlogRouteChildren = {
  MarketingBlogSlugRoute: MarketingBlogSlugRoute,
  MarketingBlogIndexRoute: MarketingBlogIndexRoute,
}

const MarketingBlogRouteWithChildren = MarketingBlogRoute._addFileChildren(
  MarketingBlogRouteChildren,
)

interface MarketingLegalRouteChildren {
  MarketingLegalSlugRoute: typeof MarketingLegalSlugRoute
  MarketingLegalIndexRoute: typeof MarketingLegalIndexRoute
}

const MarketingLegalRouteChildren: MarketingLegalRouteChildren = {
  MarketingLegalSlugRoute: MarketingLegalSlugRoute,
  MarketingLegalIndexRoute: MarketingLegalIndexRoute,
}

const MarketingLegalRouteWithChildren = MarketingLegalRoute._addFileChildren(
  MarketingLegalRouteChildren,
)

interface MarketingRouteChildren {
  MarketingBlogRoute: typeof MarketingBlogRouteWithChildren
  MarketingLegalRoute: typeof MarketingLegalRouteWithChildren
  MarketingIndexRoute: typeof MarketingIndexRoute
  MarketingProductsSlugRoute: typeof MarketingProductsSlugRoute
}

const MarketingRouteChildren: MarketingRouteChildren = {
  MarketingBlogRoute: MarketingBlogRouteWithChildren,
  MarketingLegalRoute: MarketingLegalRouteWithChildren,
  MarketingIndexRoute: MarketingIndexRoute,
  MarketingProductsSlugRoute: MarketingProductsSlugRoute,
}

const MarketingRouteWithChildren = MarketingRoute._addFileChildren(
  MarketingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  GatedRoute: GatedRouteWithChildren,
  MarketingRoute: MarketingRouteWithChildren,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiOgRoute: ApiOgRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
